
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
      - NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
      - CHOKIDAR_USEPOLLING=true
      # if CPU is high, uncomment the following snippet.
      # you can also increase the number to reduce the CPU aggressive usage.
      # - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    # insure container uses its own node_modules for consistency
    volumes: 
      - /app/node_modules
    develop:
      watch: 
        # Rebuild image when dependencies change so container picks up new packages automatically
        - path: ./package.json
          action: rebuild
        - path: ./pnpm-lock.yaml
          action: rebuild
        - path: ./next.config.ts
          target: /app/next.config.ts
          action: sync
        - path: ./tsconfig.json
          target: /app/tsconfig.json
          action: sync
        - path: .
          target: /app
          action: sync
          # ignore copy any dir of file for the hosting machine(windows, mac, linux) listed below, and use the container's own ones
          ignore:
            - node_modules/
            - .next/
            - .git/
